# Generated by Django 5.0.6 on 2024-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="box",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
